PKG=git.olympus.2s1n.in/leprasmurf/Advent_of_Code/2025/_template/B
PKG_LIST = $$(go list ./...)

include ../../../Makefile
include ../../../Makefiles/Go.mk

.PHONY: dependencies

dependencies: deps_go ## Project-specific dependencies
